columns name modified
ytcsc/TeCoLab pull request #3
Opened 2023-08-19 14:19 UTC by matheusnatanb

2023-08-20 15:16 UTC, ytcsc requested changes
The code changes are good and I'm inclined to approve the pull request. However, before we proceed with merging, please address the feedback provided in each individual file's comments. Once you've made these adjustments, the code should be ready for merging. Thank you for your efforts!

2023-08-21 12:53 UTC, matheusnatanb commented on Software/Experiments/StepResponse.csv
> +20000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Done

2023-08-21 12:53 UTC, matheusnatanb commented on Software/enums.py
Done

2023-08-21 12:53 UTC, matheusnatanb commented on Software/Modules/TCL_Experiment.py
> +from enums import CSVColumns
you're right

2023-08-26 13:10 UTC, ytcsc approved these changes

2023-08-26 13:13 UTC, merged